---
title: "Journal Creative Writing"
output: 
 rmdformats::readthedown:
    highlight: kate
html_document:
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})

  

---

# Subliminal

The Subliminal (n). 1. An imperceptible force which manifests just above the threshold of consciousness yet below the radar of perception—resting between what is there and what we can see. 2. The invisible conduit connecting the dulcet gaze of a lover’s eyes to your inner consciousness; or the silent dialogue occurring between a lover’s soul and your awe-struck countenance upon seeing her. 3. The ethereal impetus which almost, but not quite, demands you to flinch in pain when glaring deep into the eyes of one in pain; allowing you to almost, but not quite, taste their flame to live even upon the face of death; gifting you the capacity to almost, but not quite, feel their arm reaching out toward you begging to be pulled out of the bottomless pit; granting you the wisdom to almost, but not quite, hear their internal shrieks and cries demanding someone to hold them when met with vulnerability. 4. The impalpable demon which hides under the dark shadows of perceptions from which he can strike at any moment, able to even throw a god into shock.

# Smell

I find myself in the basement of the library where the aroma of isolation, abandonment, and dust strike me. It reminds me of a forgotten greek temple, full of dollops of truth and wisdom, yet left to accrue age through the hourglass of time. I walk down the aisle, as I go deeper I become entrenched with the smell--permuting into something different every step I take. I grab the first book I find labeled “Plato’s Symposium” and I open the pages not quite reading it, but reminiscing of the times I talked of love with my friends and lovers from highschool. Oh how I miss those times, the words give me a tang of reminiscence--but it's not enough. I bring the book closer to my face, smelling a sweet vanilla with a pinch of wild-grown lavender. I blink momentarily, and suddenly I realize this place isn’t full of ordinary dust, it’s pixie dust--one that makes you flutter through time like the cosmic butterfly. I grab the book by its spine, bringing my nose right to the page, and I read the story with my eyes close as i flip through the pages--one by one--letting the smells alone craft my reality. I smell the wild lavender again, and this time I find myself sitting behind my first girlfriend Lexi, arms around her back, as my face is resting on her goldilock’s hair. I close my eyes tighter, feeling me hold her even tighter, and for a moment, I am reliving this moment in the past. I start flipping the pages quicker, and I feel the quant spring breeze, bringing forth smells of vanilla, red roses, daffodils--and the sun evaporating the water following a gentle spring shower. The sun’s light permeates from behind the clouds putting us in the spotlight, she turns toward me, and I look into her eyes. I swear, I can smell them: a pinch of olive, a little bit of ocean, and forget-me-nots. I lean toward her slowly closing my eyes, her soft lips meeting mine, where I then gently place my hands behind her precious hair holding her soft neck where I breath just a little bit through my nose, and for the first time, I smell her gentle skin.  At that moment, I knew I was at the part of the symposium where aristophanes', a little tipsy and perhaps even high, says love is finding your other half. Zeus, full of envy, saw a person and person bound together--four arms and four legs rolling around exploring the earth without a care in the world. Where on this sight, he smote a divide between the two of us creating what we call humans. But I swear, the way Lexi was turned toward me, with my hand cupped behind her neck, my lips pressed against hers, gently smelling her skin. It is almost If I remember the time we were rolling around the earth, four arms and four legs, without a worry in mind. Her skin smells sweet, like an apple pie straight out of a southern oven, and it feels like we are reunited once again. At that moment, I knew she was the one, she is my lost half aristophanes was talking about. I hold her tighter, then let go, giving her a kiss on the cheek, as she turns around looking at the spring valley and I smell her golden hair once again. At this point I feel a tear run down my cheek, one that bled through the hourglass of time and onto my present face, and then suddenly the magic of the pixie dust ends as I reach the end of the page. I look at the symposium once again, and I feel the idealistic love of my youth grasp me once again for a moment, not through words but olfactory sensation. I put the book back, walking down the aisle, looking for the next memory to be delivered to me.

# Writing about a rock

How to write about a rock. You grab your 99 cent blue composition note-book, a pen--to remind you that you can’t take back your words, and your sense perceptions. You look at the rock. It is on a side-walk, but leaning against a brick wall. Nothing special. You realize there is a degree of separation between the rock as you see it, and the the poor sucker who is going to read this and needs to see past your terrible handwriting; but that is not the only thing they have to look passed. They have to look through the guise of language, at the end of the day, words are a man made construct, an empty placeholder for a sense experience we have once felt. But regardless of how much the person felt, no hallow-corpse of letters combined together can bring the sense experience of the rock. You begin to feel existential dread. It is my obligation to deliver the sense perception of this rock, regardless of the sensational gap! Language can transcend anything, there is a reason Shakespeare is timeless. He captured something no? You begin trying to describe the rock:

There lied a precious, yet forgotten, piece of the earth. It is older than the consciousness of any human to breath, and all that will come. Humans come and go, yet the rock persists. Whether you call it a curse or a blessing, it will be there. I walk closer to the rock, and begin to see faint, bright reflections of light from the sun. It is subtle, yet sublime. It is dense slate, denser than the skull of a stubborn man, unmoving in its ways. It assumes its presence over the sidewalk, a refined stone that has lost its essence. Yet it has its presence assumed over it, by the towering brick wall that looks like the tower of babel reaching the heavens. But as a rock, you can never reach the heavens; heaven is a forbidden place. Only the mortal are allowed to go, but us who are cursed to this land are forced to be stepped on by man, kicked by children, thrown into lakes when someone is going through existential dread. We are not respected, we are treated as a means to an end--nothing important. But little do they know, we make the earth that they stand on, not god!

I write all that down. But for some reason it is missing something, all of these words are unique to the human experience. It's not that a rock can’t feel existential dread. Its just the only thing I have to describe it is my experience, and this measly construct of language that cant capture anything outside my experience. I can’t get the qualitative experience of what it means to be a rock. I feel the existential dread. I just can’t write about this rock, there are so many degrees of separation: my experience to the reader, the time barrier from now to whoever would read it, and most importantly--what it means to be a rock. Anyway, if i write about the rock, I am doing the opposite. I am imposing my will onto the rock, i am the greater mediator of its experience. I cant do this! 

# Hunger

It’s 7:30pm, the sun is just now setting at the same rate my stomachs feels the pangs of emptiness—it is like clockwork. Only when the sun dives past the horizon does this hunger rise like a zombie from a tomb, regarding no one because there is no light to expose it. When this hunger rises, like a werewolf at the sight of a full moon, there is no amount of restraint that can hold back its force. It always just starts with something small, I’ll make myself a PB and J. The more I maw at the sandwich, the more the peanut butter slows down the hungry gears of my teeth. With the Peanut butter pouring down my throat like hot tar, I am still unsatisfied. I open my fridge and take out the box of leftover rotisserie chicken, you know the ones with only a little meat on the skin of its bones? I don’t even get a plate, like a child grasping at her mother's hand, I grab the chicken bare. I dress it in some honey barbeque, and I suck the bone dry like the sun does to a california raisin. With all the dry meat of the chicken falling into my abyss of a stomach, I find myself searching for my next pursuit. There is no more meat in the fridge, but there is still bread. I look around the house, one slice of bread in each hand, and notice the faint light of our 55-gallon saltwater fish tank. I walk toward the light, looking at our coral reef of a tank. I grab the thin green net sitting atop the tank, and I scoop up a handful: blue densals, yellow tangs, clown fish, and toss it right between the bread. Like a hungry child at a fair about to eat a mustard dripping hotdog, I put the sandwich between my teeth until I hear a crunch and feel the squirming of the fish in my mouth. When I swallow, it feels as if the whole ocean is swimming down my throat and into my mouth, and I realize--it is not nearly enough. I gobble the rest of the sandwich, leaving me with just the tiny bones and entrails of fish in my mouth with a lingering aftertaste of a sweet ocean breeze. I scurry around the house, not a single article of food left, dying to find my next meal. My hunger, like a child glaring at all of the candy in a store, lusts for something greater than it has ever tried. Something transcendent, something that will satisfy it! I go into the kitchen, seeing the glistening of a knife by the moonlight through the uncleaned window, and I realize, this hunger can only be satisfied within. I swiftly grab the knife, and I look at my fingers. Like a mother chopping carrots for a soup made of love, I cut each piece of my fingers at the indentation of my knuckle, and I watch the blood slowly pour out of my left hand. I toss each one into the abyss of my mouth, feeling the crunch of my fallanges that require so much force to break. But long behold, my stomach needs more. I go for my other hand, realizing that would disable me from eating more. And I realize, it needs to be deeper from within. You don’t need a kidney, before I even finish the thought, the knife is 5 inches deep in my gut. And like a child carving a pumpkin with her mother on halloween, I take out the entrails leaving nothing else inside. I close my eyes, upon feeling dizzy, and I toss it all in my mouth. It is so much, I start to choke for all of it can’t fit inside of my stomach. But for some reason, I no longer feel the pangs of hunger overcoming me. Am I finally satisfied? I close my eyes, and like a child about to take a nap after a loving thanksgiving dinner, I fall onto the floor trying throw a smile on my face even though my mouth is completely full. 

# A chair for every role

I walk into my lab, shoulders high, ready to work on the manuscript I am submitting for the conference at UMass, the R statistical analyses for one of the research projects, read a couple of the new journal articles on volume 198 of Cognition, meet with Sara to norm those stimuli that should have been done last tuesday—and a few other things I can’t seem to remember. There are a total of 7 chairs in the lab, one for each day of the week, but I am unsure if that really is the case. I take a seat on the somewhat comfortable fabric of the sturdy and reliable office chair. I reach into my bag to take out the following: my laptop, my notebook, 20mg of Adderall IR, a pencil, and the “Conceptions of the Mind” Edited by Gilbert Harman. I realize the chair is raised up. Its slightly discomforting. I reach under the chair to pull it down, but I fail to find it until a couple seconds pass by; Then quickly, I ascend downward, at the level of a true scientist which is near the earth where “foundation” lies, hunched over now typing computer code vehemently on my laptop. Five hours pass by, and my back is as tense as my mind trying to understand how the (Balota et. al, 1975) study on “The interaction of contextual constraints and parafoveal visual information in reading” related to “The role of preview validity in predictability and frequency effects on eye movements in reading” by Staub and Goddard (2019). I lean back as far as possible, feeling and hearing the crackling sounds a fire emits in a campfire as I crack my back--and then I lean back into the chair feeling perplexed. I bring the pencil to my head, thinking hard, and begin to push the chair across the high friction carpet resisting me from pushing too far. I can’t seem to find the answer. I find myself dizzy, I am spinning on chair as my thoughts race in circles. I look up and close my eyes, and I can still feel the spinning of the chair even though it is completely still.

I’m in the waiting room of the psychiatry office, not feeling particularly happy nor sad—just perfectly indifferent. I am sitting on a chair that is slightly too small for my torso. But it will do. I try to put my arms on the arm rest; however, the cold plastic on top of the weird angle makes it too uncomfortable to use. I instead lay back on the chair, shoulder crossed like a pretzel, as I sit there with a mere modicum of anxiety waiting for them to call my name. I have been in this chair a dozen times before—or at least ones similar to it. It feels like the seat you wait in before a trial: you are not quite on the hot seat yet, but you're getting there. You are thinking of your alibi as quickly as you can, but your thoughts are a little too disorganized to—”Alex?”, said the nurse. “I’ll be right there”

I'm sitting on the balcony of a girl I met on tinder, her name is Brooke. I am on the archetypal metal chair, you know, the foldable kind you can find at Walmart for a few bucks?—college students aren’t rich you know. Though the cold back of the chair is making my back feel a little chilly due to the cold, cold metal—I feel utmost comfort. She is smoking a cigarette, and so is her roommate. The three of us are looking out into the parking lot as we see only one car, lights are on, blasting pink floyd and clearly blazing a blunt. We all chuckle a little, “haven't we all been there before at least once”? Said Brooke, and my chuckle evolves to a full on laugh as I put my arms around her. The the chair creaks a little, but in the best way possible. She leans on me, sitting on a chair just like mine, and we look at the sublime skyline of the parking lot: the sky permutes from celedon, to crimson red, and then a royal purple. I bring my metal chair closer to hers as I hear the screeching from the concrete floor and the metal legs, and then I hold her closer. Her roommate goes, “man, this is a vibe”, and I respond “yeah, definitely a vibe”. This is followed by the most quaint silence as we look into the sky, watching god sprinkle the sky full of a variety of different stars.

I am sitting in one of Brian’s dining room chairs, it's a little old, yet you know when they got it it was excellent in quality. The chair is slightly beat up from all of the memories we have shared at this table: all the times meric the rogue sneak attacked our enemies, the times Dayman Demsi activated his banishing smite knocking the evil out of this place, and event that one time galarkadark tried to hit on that high elf at the bar--you know, the rich one from the Therafold family? The chair is a little wobbly, one of the legs seems a little shorter than the other, but its no biggie—its not like it can remove me from the world of Ebberon. I remember we are at waterdeep, and Garr, the elemental prince of the seas, has just summoned a Kraken releasing his wrath onto the town. Galarkadark, the king of Phandelon, and my best friend, yells toward me: “Fidemacus! We must do our tag team combo!” I imbue magic energy into my hand, touching my torso as magical energy permeates through my dragonborn scales gifting me the ability to fly like my ancestors. I grab Galarakadark Stormforth, propelling at mach speed up into the air as I release him into a free fall. He begins to que his battle cry, as I charge up my lightning bolt spell, aiming not for the kraken, but his great heirloom great axe. I jump out of my seat, as I hear the screeching of the wobbly legs, with the chair about to tip over as the dungeon master quickly exclaims “Alex, the chair!”. “Oh yeah, sorry!”, yet I remain standing awkwardly hovering over the chair I have been sitting on for years. My lightning bolt strikes Galarkadark’s axe, going what seems faster than the speed of light itself. His Axe all charged up, he begins to spin preparing for his first attack. The kraken brings up its two strongest tentacles, ready to swat him like a fly, as he instead slices them off clean right then and there as we hear the screams of the kraken. Garr is pissed, and next thing he knows he hears a thunderous boom as i teleport right next to him, holding his arms down as Galarkadark runs up aiming for his head. I sit back down on the wobbly chair at the thought of that, with Lorenzo, who I consider my 12 year old cousin by heart, leaning on my arm as he looks up at me and exclaims. Alex, Alex, Alex! Can Meric the Rouge the Fidemacus do a tag team attack! And I look him, with the same countence Fidemacus uses following a victory, and I say “Of Course!” in fidemacus’s voice.

# Day in the Lab

Today was a gorgeous day. Albeit I woke up at 6:47 am when I needed to be in my car, out of my apartment complex, and on 57th avenue waiting at that one traffic light--you know the one that just doesn’t turn green?--by 6:47 am. I was able to get there by 6:53 thankfully, where some asshole cut me off--that guy got what he deserved. Regardless, when I got to school I gazed toward the somber autumn leaves that painted a scenery with pinches of red, splashes of brown, and dollops of yellow highlighting the backdrop of Linsly-Chittenden hall and the Connecticut sunrise. It was like any ordinary day though, I saw Jacob, the senior research assistant, walking into connecticut hall where the “Neurodevelopmental biology lab” resides in. He was carrying his daily lunch, nothing too special or out of the ordinary. I catch up to him, uncomfortably pushing myself toward him almost slipping on the somewhat watered down ice on the sidewalk. I walk through the front of the building, where debera, you know the secretary, is about to check our ID’s. Someone is in front of us, holding up the line, and due to debera’s impatience--you know how she gets--her pupils dilate to looking like one of those silly house cats, where she opens a portal underneath the Joshua, the new temps feet, dropping him into the abyssal plane for at least a couple of years. Ofcourse, time moves differently there, a few seconds are a couple years. We have all been there, it's totally crazy when Cerberus that one time indefinitely ripped my limbs as they grow back instantaneously. I have no idea how she does it! Debera gives her quirky laugh, you know the one she gives every time Steven, the lab manager, tells jokes about the weather. Her eyes go back to normal, she scans our cards, and we walk through the entrance and wish her a good day. What would the lab be without her! 

# Light

I sit in somber silence, waiting for the next light \
I’m sure once I see it, it’ll look so fucking bright \
I sit in somber silence, reflecting on all the previous light\
I’m always sure when I get it, it will be the end of my plight\

I feel a void deep down, patiently waiting for it to be filled\
I hopefully close my eyes, anticipating when ill be fulfilled\
I open my eyes wide, and can’t believe my eyes\
I feel an impetus within, gifting me energy to get the prize.\

I run and I run, seeing the light permute into a figure\
I notice a beautiful woman, I proceed to run quicker and quicker\
I ponder and I ponder, this undeniably has to be the one\
I finally come to greet her, we stand here one-on-one.\

I listen to her voice so dulcet, she is indeed drop-dead gorgeous\
“I think you are everything I want, here is the way into my fortress”\
“I have been waiting for the one, my love for you is enourmous”\
I listen in pure euphoria, but it simmers down as I feel cautious\

I sit in immense confusion, trying to keep a countenance of magical intrigue\
I feel my heart stops pounding, was it my run that resulted in this fatigue?\
I realize it was never the light I yearned, but its pursuit that felt like a blitzkrieg\
I am enlightened I understand, there is something unsettling about resolve indeed\

I always gaze to the outside world, seeking the attainment of this light\
I always try to grasp the light, but its amorphous form never feels right\
I realize the hunt and the pursuit is what provides me with pure delight\
I realize the light is innocuous, for the pursuit was all I needed all right\

# Chillin'

There I am, on a quaint summer night, enjoying the simple things. The cool sea breeze following a gorgeous California sunset, a hotel porch with two plastic chairs, the presence of a woman, and a joint. I light up the joint just as the sun dives down into the depths of the sea, take a few hits, and pass it to the beauty. I sit there in silence. I stare at the sky, watching the clouds change color and glide, as the stars begin to paint the purple sky with bright light. I begin to feel weightless: free from school, work, past experiences, and all other obligations. The first few times this escape felt extricating, but like any routine, it’s bound to become just as mundane as everything else. I shake the thought and imagine I’m on the cloud, sailing a boat into a world that once seemed so unknown, but know feels as familiar as the back of my hand. As my boat ascends higher than mt. Kilimanjaro itself, I recede deeper and deeper into my chair.

# Second at the bar

I find myself surveying the polish of the Mahogany bar counter while waiting for my empty drink to be refilled. My pensiveness begins to permute into a form of thoughtlessness as my mind detaches and my eyes wander--unaffected by reason or will--only left to drift away from the body into the immense sea of woodgrain imprinted on the surface. Indubitably, the wood pattern is stagnant and inplace naturally; yet, it appears as if the spirals of the woodgrain begin to spin around itself: some clockwise, and others counter--not only to the clock--but to reality. Independent from rumination, my eyes begin to float, nearly sinking, atop this sea of dark wood that is unscrupulously twisted by an unfathomable storm. Its formerly detailed stagnancy escapes me completely, as it was washed by the swaying waves of brownness fluttering circularly about this former tree’s blood-red heart to where it seemed I became one with it. Movement and flux manifest ubiquitously in this ocean, leaving you unmoored from any anchor and indefinitely far from land: its beauty and immensity is liberating--yet one can’t help feeling lost. Suddenly, it begins raining this bronze like liquid from the cloudless sky that starts to sink my boat and burn my eyes; the sting of the whiskey is the last thing felt as my eyes sink into the abyss of the woody waters, forcing my mind and eyes to become one again. I blink, then glance at the bartender pouring the intoxicating syrup from an ostensibly half-empty bottle of whiskey: I say “thank you sir”, and before he gets the chance to hear me, he is already pouring a drink for the fine lady two stools from mine.

I take one more sip of my drink feeling the bitter taste burn blissfully down my throat as I rotate the stool to look forward. Asudden, my eyes are barraged by free-form chaos in the form women and men dancing fiercely to rhythmic music coupled with lights of every color: blue,  yellow, green, and red all shining on specific details of the scene while moving in a pattern I can’t fully discern. My eyes follow some of lights as I try internalize the scene; however, the lights aren’t bright enough for me to see the holism of the nightclub. My eyes are mesmerized by what the light elucidates, and what I see penetrates my somber mood and metamorphosizes it to become euphoric. moving quick enough so your mind can’t process what is being seen. 

# The Vibe

Words can't describe the Vibe\
You'll understand when you submit control\
Language always tries to confine\
Just close your eyes and let it compose\

The music starts to sound so sublime\
You begin to move without control\
You beg for freedom but the request is denied\
The music appears to have a mind of its own\

Your arms and legs dance to comply\
Your eyes close seeing past the plateau\
Your body moves yet your essence is paralyzed\
The music puppets you around like a cyclone\

The song begins to obfuscate time\
The music suspends the arrival of tomorrow\
It feels like you'll be trapped in the night\
Looping inside the unending song of the unknown\

Your arms and legs dance to comply\
You beg for freedom but the request is denied\
Just close your eyes and let it compose \
Looping inside the unending song of the unknown\


# Lost in the currents

Where is the line between sobriety and inebriation?\
I can't see myself anymore, am I an abomination?\
Why do I drift afloat the river of demeaning words and conflagration?\
Why do i choose the lurky waters of self-hatred at the face of salvation\
Why do the hands pulling me down gift me with such validation?\
Where do I demarcate between self confirmation and others' indignation?\
I can't recognize myself in the mirror, do I need medication?\
Why does the prospect of drowning in these waters insue no trepidation?\
Why do I surrender to the current instead of reaching for the helping-hands of appreciation?\
Why do I have so much to prove to the ones who try everything to forestall my salvation?\

Why all these questions?\
Self-rumination: preventing rehabilitation,\
enhancing obfuscation, robbing me of revelation.\

What is stopping me from swimming to the shore and initiating my transformation?\

# Sensation

Hearts racing, minds pacing\
Eyes of blue fire and intimidation\
Musics playing, candles blazing\
Lava pink lips that are full of amazement\

A voice of graceful promise\
It hugs me, and i feel rejoice\
An aroma of dulcet solace\
It pervades me, I taste the joy\

Sensation: intertwining and binding;\
binding and intertwining\

A touch of perfumed calmness\
It imbues me, I hear purity\
A taste of tangy fondness\
It invades me, i smell the chemistry\

Sensation: intertwining and binding;\
binding and intertwining\

# Poem

His name is Bill and he lives on a mountain, [hillside]
Except that is a lie; he lives on a beach, the true place in which he surmounts in.
Living on the brink of poetic perception, humanity makes him feel paralyzed,
Probably because you made a preconception; you are a subjective pair of eyes
Space— does not exist beyond language my dear reader. You are a presumptuous fuck!
My name is Arthur, the author of this poem; like that line, I had to be authorized,
Everything to be understood must be approved by what the eloquent author eyed
!I am stuck in Rhyme. This prose fucking sickens me, people only listen when there is pure
Symmetry;
Bill is me and I am Bill; we exist volitionally, just like language and thought.
This poem can not exist beyond this page!

# Love

Many individuals are oppressed by the superincumbent feeling of existence and naturally the subsequent thought man would ponder would be its purpose. There are an infinite amount of possibilities that the future may reap overwhelming man’s senses; since man is always vulnerable to oversight of future, we tend to recede into our own ego to find an answer to it all. As people, we have one ability, and that is the power to rationally analyze the past and the present spawning a plethora of emotions that are strictly subjected to humanity: from memories to nostalgia, from dreams to desires and from adversity to understanding. All of the emotions that erect from this phenomenon both define humanity and provide us with a palpable understanding of the present. However, this gift comes with one ubiquitous and tormenting force that has consumed humanity for ages and that is how our extensive abilities to look into the past is juxtaposed with our inability to predict or view what lies in the future. This juxtaposition is where all of the paradoxical emotions of man rise, where we are forced to come up with new emotions that leave us with a bitter sweet taste. The past not only defines the present but invasively penetrates the future. Suddenly our nostalgia becomes longing, our desires become ambitions, and our understanding branches off into a dichotomy of a million emotions that define the world of our future that so hauntingly remains unknown blooming the most platonic emotions that make us us; the best of them being love.

Just like a blooming flower, feelings that the future creates are never really stagnant like former emotions defined by the past like happiness, joy, sadness, and nostalgia but are rather manifested in a dynamic and changing feeling that is catalyzed by the uncertainty that lies in the future. This fleeing feeling derived from the future is a postmodern enigma that would constantly disturb the stationary fulfillment that humanity attempts to pursue due to their inability to understand what results in the future. A Phenomena that must be defined under strictly paradoxical and antithetical foundations. Every single emotion derived from the future is unable to become or manifest due to one underlying fear that lies universally amongst people; uncertainty. Uncertainty is paired with these emotions commonly: from the balancing of ambition and fear, to the balancing of love and fear. Love contains a duplicitous nature to it that allows ideas of passion, trust, care, admiration, and intimacy to be superimposed next to feelings of doubt, insecurity, jealousy, and panic -- ostensibly paradoxical and outwardly confusing -- yet an imperative feeling that humanity and I must have to feel the most profound of connections. Though we have no idea how a gatsby-esque pursuit may result in, it acts as a conduit between two individuals that provides a force that allows individuals to cope with the existentialist void that exists.

Love cannot exist without the subordinate opposite emotion, it is an unstable yet stagnant connection that provides us comfort and fulfillment. From an existentialist point of view, life provides meaning that is objectively non-existent subsequently leading us as humanity to fill the void with aggrandized ideas we create, love being one of these essential -- or existential -- emotions. Without the uncertainty of the future as a variable that controls the power of love, love would cease to exist, it is the malleable and uncontrollable nature of the emotion that allows it to be so intimate. Epistemologists or Romantics may pose the argument that Love is something that is predestined and transcends the fundamental natures of the past, present and future; however, once one no longer has control over the decision to chose to love, the imagination and infinite possibility that spawns with the notion of love are effaced. It is the infinite and immense possibility that results in the pursuit of love that defines its gratification: the idea of where a couple will live, the color a couple will pick for a bathroom, the location of a couple's marriage, the cemetery where a couple will get buried or the date a couple would break up due to incompatibility. Without the elements of ambivalence and pain that are associated with love, all the chaotic emotions of trust, care, passion, intimacy, and hope would all cease to exist. Sometimes it is the lack of things that is carved within an eternal stone that provides a stone it's comforting and eternal meaning; an empty impalpable template that represents the blooming future that can't be touched by man, but metaphysically caressed with the love of two individuals who seek fulfillment. Just a tease to understanding the ubiquitous paradoxical enigma of life.

# Nostalgia

The manifestation of the nostalgia when observed subjectively is the superimposition of an infinite amount of memories and emotions that we, cathartically, grasp on as if it is our stable conduit of comfort and becoming. The strength of said connection may apparently seem tenacious, however when analyzed beyond the eyes of man, the kinship is simply a tenuous facade that is formed by the blindly shichtinliating forces of the possible future and the grotesque present. However, man so audaciously proceeds through the sandstorm of existence, unable to see the evidently conspicuous present that is manifesting with every arduous step through the sand; We close our eyes and recede into the deepest parts of our memories to project a path onto the chaotic sand storm, subsequently granting our past the privilege to unscrupulously guide us through the unknown. As autonomous beings that inevitably need to progress towards the future, we ironically suffer from the incapability to remove the malleable and selective memory that ubiquitously controls us while erecting our motivations, ambitions, and goals. Modernists may call it the defining human element, However I call it a purgative necessity that controls us blindly while binding us in constant denial and disillusionment. 

# Remembering Love

I lie there by the quaint and tranquil pond spectating the robust transformation of the sky, my perceptions begin to warp and deform as the sky undergoes a metamorphosis that is truly incomprehensible to the human eye: the hues of blue that appeared to be so definite and indubitable suddenly collapse into a dark purple blotch of nothingness, the clouds that spawned at infinitum to resemble all kinds of consistencies and arrangements suddenly grew homogeneous due to  arrival of impending darkness, and the bright and vivid reflection of myself on the cozy pond that is crafted only from the light of day acutely becomes invisible as the sublime sun begins to set, ultimately, disabling myself to even see myself in the reflection of the pond. I lie there alone. Unable to see anything, the ostensibly timeless sunset that seemed to last forever suddenly felt like an instant; I sit there pondering, no desiring, for only one thing, and that is something that is definite and secure in this world that doesn’t undergo permutation. Time progresses as we try to capture the moment for ourselves, and the rain arrives as we try to linger in the meridian of sunlight that is so fulfilling; however, there must be something immutable in this existence of change, and that is love. The sun has left no trace of visibility leaving me in true darkness, I then close my eyes and generate myself next to my love, Kaelan: I imagine her soft hands wrapping around mine in the darkness of my closed eyelids, filling me with hospitality and warmth; I envision the phenomenal glow of her eyes meet mine, as the dank and moist grass i am sitting on physically seems to no longer exist; I fabricate the feeling of her soft and inviting kiss against my lips to where i no longer feel as if I am in the humid and hot air of the florida weather, but rather that i am on her twin sized bed -- that so happens to be in the closet -- back at her old house after school, comforted by both her sweet touch and rainbow lights. I sit there on the bed, where both her and I polymerize ourselves from two different objects into one. We hold each other very close, and very tightly, as time begins to feel rather stagnant while my senses are sharpened: I feel the silky bed sheets beneath my legs, i feel the wooly texture of her cardigan as she wraps her arms around me, and i feel all the aloof hairs from her head gently tickling my cheeks as i giggle. I take a glance at my wrist, quickly realizing this was the one day i forget my watch at home this week, and I integrate my tongue with hers. My whole reality begins to numb, and slow down even further in this second, I am debating whether i should keep staring into the indefinite beauty of her eyes, or close them to enhance the feeling of her tongue on mine -- senselessly, I close my eyes. I feel like i am inside of her forever, and i linger as long as possible. I feel this nervous sensation in my heart as it begins to pound at a significantly slower pace, yet with an intensity far greater than the blast of a hypernova. I find myself standing in an awkward position as her arms are wrapped tightly around mine, as my eyes are still closed. When they open, I find myself in front of her door at 6:17 --  i think -- in the morning, finding myself in complete awe and complete shock to the idea of her going to homecoming with me. Though this moment seemed independent from all petty worldly things such as time, school, and work, we open our eyes and walk to my mom's car to go to school. Time begins to progress from completely frozen to moving ever so slightly, though it resumed movement, we both know we are in control of all worldly problems since our love is stronger than everything and anything. We both sit on the cold leather of my mother’s lexus, holding each other's hands for warmth, towards dunkin’ donuts. The feeling of the warmth of my hand engulfing the cold yet soft temperature of your hands places a huge smile on my face -- i proceed to hold it tighter and tighter because I know it is my privilege to keep her warm in this absurd world. I look at the time and forget that the clock on my mothers car is broken, and before we know it we arrive at dunkin’ donuts. You get an unnecessarily iced drink in the cold weather, as i get a terribly hot coffee for my poor tongue. We stand there still holding hands, and next thing we realize we are already at school, in Mr. Bodines room. It is then, we realize, that we forgot to capture the moment from before on camera and we can never look back on the time “i asked her out for homecoming”; we quickly try to compensate by taking a photo of us, while i am wrapped in your comfy plaid sweater, while there is the biggest smile on both of our faces. I feel complete warmth and happiness, and i look at the clock on his wall to check what time the bell rings, and it is already 7:05. I open my eyes, and i only see darkness. I am reminded that I am still outside near the pond: I am still sitting on the dank and moist grass, I still feel the hot humid air of the florida climate -- and, suddenly, i once again feel the ubiquity of darkness and loneliness that was there before I briefly closed my eyes in the first place. Though i feel sweaty and uncomfortable, i am comfortably reminded that of all the worldly things that change around me such as the setting sun, or the passage of time, kaelan is my anchor that i can always rely on. I realize that i didn't need the photo from when i asked you out to homecoming, all i needed to do was close my eyes and experience the raw emotion just like it was when i did it. Sure i won't remember what type of coffee you ordered that morning, but that emotion i felt will always linger, like an undying flame, deep inside my heart. I blink one more time; then, I open up my phone and see the hangout notification. I am then removed from my romantic recollection of all of my memories with her, and i am met with us in the middle of an argument. I feel perplexed really, yet also rather apathetic of the details of the argument. I understand she is upset because i am not there for her, and it all comes from her heart; yet, the only thing i can respond in my right mind with is emotionless “okay”.

# The Woodpecker

I find myself sitting on a rugged bench four feet from the lake, though the bench is a bit old, as well as moist from the afternoon thunderstorm, the view of the sublime lake that defined my childhood mesmerizes me: I lie there in opulence as i am gifted with the warm yet soothing breeze brush against the hairs of my cheek, I am filled with awe as the rays of the sun penetrate through the dark clouds providing my body with comforting warmth, and i feel an immense amount of wonderment as the ospreys so gracefully yet confidently soar above the lake, looking for food. As i lie there, I vividly recall the numerous amount of times that I came here as a child, mindlessly and foolishly jumping and playing, as i immerse in the intricacies of the park. I can almost feel the feather-like weight extricating my past self from worldly problems such as gravity and physics, where the only thing i can think about is how beautiful the quaker parrots look when the occupy the sky in flocks of hundreds or maybe even thousands, as I leap upward trying to catch one to be my friend. I blink, and I am gently removed from my flashback and placed back to the present. I briefly look away from the indefinitely large lake that i cannot even see the end of, and i calmly look around: I observe the man-made peninsula i am sitting on that stems about 200 yards from the park, I admire the classic, red-brick, lighthouse that is there more for novelty than for anything practical right at the edge of the peninsula, and I feel contentment as my best friend and her girlfriend sit right next to me, tangled like a pretzel in a hug, enjoying each other in such a soothing environment.

The clouds that latterly lurked right above us once skewed our perceptions with its unmitigating winds, and uproarious rain; however, that time of ardour quickly lapsed, since all I can feel is the tranquilizing feeling of the orange-yellow sky filling my skin with life, and the bona fide love that emanates from the couple right next to me. Without any words, my friend gazes towards the horizon, and points out the beginning developments of a rainbow, that radiates with lively glamour, fulfilling all forms of life with exuberance: to all people, plants, and animals alike. I glare in admiration to the beautiful rainbow, then i turn to look at him and give him an affirming and validating countenance that is worth a thousand words. He then goes from looking at me, his best friend; to looking at his girlfriend, the love he wishes to savour; then, the dark part of the sky that is filled with fog, and nebulosity. I stare at him, intently gazing, obviously pensive--but an equal possibility of having no thoughts. I look closer at his untrimmed beard hairs, gently blowing from the side of the sky that is still lurky, and for some reason i feel the dank breeze of a connecticut fall. Although, one may say that this is the story of the bright rainbow being the pursuant of what follows the rain; but, i quickly realize it's about looking back (or should i say forwards) at the enigmatic clouds that are drifting away, trying to see if there is some nugget of life to be found there. His Girlfriend is looking at the rainbow, snuggling in his warmth, as he periodically looks back at the storm that once was. I freeze this moment as long as I can, no one sees i am staring, but i feel like the passage of time suddenly froze. I hear the systematic knocking from before in my head . 


The knocking in my head comes back, i close my eyes briefly as i rub my head, and suddenly all the memories come alive. It was three weeks back from today, and I am at my friends house. We both feel as if we need to go to a funeral to a death that has not yet occurred, and we try to ignore this inevitability by relapsing all of defining memories of our past. We had lots of crazy moments together: the moment we listened to that song, “Smell” by that band Laft Funk; the countless nights we discussed our dreams and fears of embracing the nebulous and enigmatic storm known as life; and the late night walks around the pond in my old neighborhood. It's quite funny, we walked for hours around that pond, but at the end of the day, it was just a circle: both our ideas, and thoughts, in tangent to one another, went around that circle. Those circular walks and conversations were always the best for some reason, because it was something we could relive over and over again--when life naturally demands us to pick a path and not turn back. Sure, we had these walks throughout the progression of our friendship at different times, but within the walks Temporality just ceased for some reason. But now for some reason the walks just ceased, as the passage of Temporality pushes us forward. That irony is sad; but as Mr. Ampersand put it, “you need to keep a laughable and ironic distance from it”. I guess he has a point. We always talked about how we together would charge into the enigmatic storm of the future, ever since the birth of us(italicized)-- but that's not life; that's our sophomoric selfs walking in circles about what lies beyond, talking about how we can tame it together. But no one tames a storm, not even the storm itself. 

We sit in the middle of my friend’s living room, it is poorly lighted and there is only one window that hardly lets enough light into the room. Yet, oddly, I am still comforted by the light of his presence. We sit there, with nothing else to talk about--however, for some reason we both keep yearning to come back here after school to sit in this dank room. For some ironic reason, the lack of meaningful discourse is the inherent virtue we wish to preserve in the conversation--the feeling of just having the other there. It’s not like we are doing anything, we are just playing that dumb game about the crazy’s meat unicycle, and the handsome guy. What about this absurd process is comforting, and what about it makes the departure easier? We both depart into a virtual world together, twirling our thumbs in circles, dying and respawning back from when we died, versing the same boss fight over and over again. It was almost as if we were vicariously reliving the circular walks, by playing a circular game--and we preferred that since...well...Temporality ostensibly disappears in the circular game world; and the temporality that seemed absent on our circular walks, is now, forever present. The walk is no longer a circle, but a line, and line we are forced to walk. Sure, we can walk, but why do that when we have the game--the walk would only remind us what is at the end of the line of temporality, and that is the departure. 

It’s late, we turn off the game. We want to say something to each other, but it seems like there is nothing else to say. It would be a mindless, parrot like, reiteration of what was already said during our years of long, circular, walks. So i leave. It is obviously gloomy and rainy outside, and i drive out of his neighborhood and quickly race to my father’s house since he demanded i was to be home an hour ago. The crisp feeling of the cold car air conditioning, blows on the wet water droplets on the few arm hairs i have, and on the clothes i am wearing that partially got wet from the walk from my friends doorstep to my car. I feel an unavoidable anguish, and despair, i stare at the windshield wipers going back, and forth; back, and forth; back, and forth; back, and forth--i envy them. The envy i feel contains an infinite amount of disdain, and it overcomes me. As much as i want to live in a circle, I know that i must keep driving forwards, and so must my friend--i try to realize that is what must happen, yet i drive in a state of forced denial. Suddenly----a little woodpecker is spotted on the road, dying. I almost run it over, then i turn back around hoping for it to not be dead. My heartbeat is beating bombastically as if it were a bomb that was ‘bout to burst. It’s wing, and its leg was broken. I gently pick it up as i hear the painful and dying chirps of its suffering. I bring it in the car with me and i drive home. My antecedent emotions of anguish were suddenly replaced by a fucked up adrenaline. As a child, I always dreamed of one day being able to nurse an injured bird to health: but the idea of wanting to nurse a bird to health, was hoping the bird would get hurt in the first place. This sadistic feeling is overwhelming, since it makes me happy i can help the woodpecker while it torments me to why i wanted to wish for such a thing. I wanted to do everything i could to make it better, everything in my life froze, temporality itself, and the only thing i yearned to do was do anything i could to make this bird better, so he can be knocking on trees for the rest of his life, over and over again. 

I get home, in panic, and the bird is suffering, trying to follow the light of death. Despite its desire, or destiny, to follow the light--i tried my hardest to force it to linger through the pain of suffering in life. I tried so hard to feed it; give it water; calm it down--and i knew some how there was a way to stop the temporal progression from life to death. I wanted to give it all i had, and all i can ever produce, even if that meant a piece of my life. I stared into its eyes so deeply, and I saw its soul: within it was a life force that was powerful and unmitigating; a demand to knock, and get what it wants right away; and a dauntlessness that was met by no other creature in the animal kingdom. Yet, suddenly--it had a seizure and died as i was staring deeply into its eyes. I never stopped looking at its eyes, and its eyes did not change with the departure to death. It was the same as before. But i suddenly realize that the the life I saw within its dying eyes was not of its essence, but was instead a sadistic and selfish projection of my desires and dreams for it to live on -- despite, its prophetic need to die. In a sense, I was trying to preserve the circular, and absurd life of the woodpecker so it can go back--doing what they do day in and day out. I took the woodpecker as an impetus for me to preserve what must not end, and boldly stand against the temporal progression of time itself--so i can stay with my friend. I begin to sob, and what started as a gentle sob fostered into a shriek of pain equal to that the woodpecker  suffered. My Shriek was directed to something, or someone, i knew it deep inside. But i also knew its source was derived from that same selfish desire that demanded i preserved the circular life of the woodpecker for myself, the same way i wanted to preserve the circular ontology of my friendship. The Shrieking then grows into a hysteria, and as much as i wish for me to rationally think at this point--thought and rationality cease completely in my mind, and the pain grows stronger; growing into a throbbing pain; and finally, into the most refined pain that can only be described as a non-stop knocking on my brain that is both sharp and repetitive. I scream from one last time, then the knocking in my head slowly subsides into an everyday headache. Suddenly, i realize time is passing by, and I sit there looking at the dead bird in my hand. At this point the indifferent passage of time has taken what it can with it once again, and i am left with its remains. I was thinking about where to put the body, or whether i should bury it in the first place. The fact i contemplate this is absurd since not even i can believe the bird is just going to come back to life, and fly away. And since not even i, due to my selfishness, can come to terms with its death--I chose to toss it in the waste bin outside. For its departure is too much to bear.

I find myself in lost in the enigmatic storm of life, I don’t actually know where i am, but all i know is that it is cold, it is snowing, and I am climbing up a mountain with much ardour. I feel my quadriceps burning and mechanically demanding for the remaining amounts of  glycogen in my liver that i need to continue hiking towards a destination not even i know where it lies: it could be the mountaintop; but even then, what would that even mean? The world, though clearly indifferent, seems to be imposing a vibe full of avidity onto me, as if i am supposed to care for the absurd destination that lies ahead--this moralization is what forces me to keep moving, despite the lack of oxygen coming from the air, into my lungs, and then into my bloodstream. Suddenly, my insatiable desire to eat the world overcomes the pain i feel from the hike. It consumes at me vigorously and i just pray for it to disappear, I wish for something to come. Then on the brink of death, i feel warmth approaching, i don’t know where. But this impetus to find the warmth in the storm pushes me harder than before, i finally find a cave, hidden from all of the wind, and inside there is a well light fire. A cave akin to that conceived in Plato’s republic, except when i look outside there is clearly no sun; only a storm covering up the whole foreseeable world--so i walk in. By the fire i see a warm creature, among all the darkness and the unbearable cold: it is holding a white bag with lots of mysterious stuff inside of it, and it had the colors red and white over its body. I lean over to to see what it is, and it turns around, with a countenance that is both timid and afraid; yet, knowing in that all it wanted to do was be my friend and help. I try to speak, not realizing how painful it would be if i tried since i haven't talked at all in the hike, and i say in a raspy whisper “delibird?”. It turns to me and smiles, it then reaches into its bag, and hands me an oran berry: I take it with much gratitude, and it provides me with a rejuvenating feeling that gives me life, and exuberance; it is clearly the symbol of the birth of a new friendship. I then say, “thank you, but what are you thinking of?”. It remains silent, but its countenance of wonderment and care remains. It then hands me an enigma berry, of course i am confused since this berry is basically unattainable: i take it with much gratitude, and as i am eating it, i eat it a lot slower than the oran berry--for some reason, it implored that i looked away from the fire in the cave, and out into the enigmatic storm known as life. I wonder why it is all there, then i finish the berry. The hunger that was genetic to my condition, was lifted; but, for some reason, a greater hunger arrived that was more philosophical. I stare at the storm, that i seem so distant from, then i turn back to delibird. He rubs his tummy, and points to me. I indicate I am no longer hungry, but he pulls one last berry out of the bag, the starf berry: I admire its shape and colors, and when i look deep into each color it feels as if i am staring at the infinite possibilities i can pursue as a person. This berry is a lot bigger than the other two, and it tastes a lot different from the others: i taste occasional spiciness, spontaneous sourness, a surprising saltiness, and a somewhat reassuring bitterness, and an implicit saltiness that is hardly noticeable. I feel perplexed, yet comforted--comforted in the sense the prowess of the absurd storm suddenly seemed to be placed in my own hands now.

I sit down next to the delibird, right by the fire. I soon forget about the storm, temporarily. The Delibird pulls out numerous berries from its bag, and we both begin eating all kinds, yet i can’t recall the names of each. I find myself forgetting about the outside storm inside of the cave, and i fall in love with the fun shapes its flame makes in the shadows; the taste of the berries and its abundance; and the the everlasting friendship I made with delibird. Delibird never talks, I am not even sure if i recall him talking in the four years we were inside the cave. Occasionally, Delibird would make a gesture, or a face, or an action that i clearly understood. I always seemed to understand him, despite his tendency to be the wallflower in a room--even if it is only the two of us. Eventually, within the comforts of this dream, i hear a knocking, a strong and tenacious knocking in my head. I ask Delibird, “Do you have a berry to help with the knocking?” He stares at me, and shakes his head; he is clearly aware of what is happening, yet knows nothing can be done. I begin to feel the pain in greater, and greater magnitudes--and i don't know what the source of it is. Slowly, the knocking grows more familiar, and the Delibird is sharing a countenance with me that is clearly indicating that it knows what i am hearing. I feel like the knocking is demanding something from us, or something from him. Suddenly, Delibird picks up his bag of endless berries, and he looks out of the cave and right into the storm. I scream and tell him to not leave, even though i myself was walking down that path, and did not intend to go astray. He begins to wobble away from the fire, and stand right between the threshold of what is life, and what is this. The knocking grows stronger, and at this point i know that the knocker is demanding for delibird to leave the cave, but i run towards Delibird and he flies away--into the depths of the storm. I know he didn't want to leave, but why did he leave? I chase his trail hoping there is some way for me to have him stay, why does he have to follow the knocking i thought? The knocking of opportunity. 
	I clearly get lost, and right when i think i see delibird, It was just the woodpecker--dead. So dead, more dead than any dead thing the devil can possibly conceive in his worst nightmare. The knocking lingers and torments me, and so does the smell of its corpse haunt me. I then realize that this is all i dream, i let the knocking and the foul smell take me away with the storm. I wake up and i am super sweaty. 

That was clearly a dream, why would i be lost in that storm? But now i find myself in a dark room, i try to look out a window but i see a complete void of matter. I smell a strong odor of some Arroz Congri cooked an hour ago, I can tell it is very dried up by now. This is clearly a small section 8 household. I soon see dim light that leads me out of the dark room i was in, the room i was in looked like the master bedroom. I see the faint flickering lights of a candle in the other room, and I see a single mom and her chubby child. I now see the Arroz Congri, some luke warm pernil, and opened bags of marshmallows. People gather around the kid, with the flame of his future placed in the dead center of the universe, the town, the house, the family, and the cake: he closes his eyes, and wishes. Then he blows. From the smell of the smoke emanating from the candle, i knew the wish, and the wish was the same wish as always: Only if pokemon were real. I feel the same way, and wish the same thing. Too bad the only “Wish” coming true is the calling of the storm to take you north, all the way north to where the books are plentiful, and so are the opportunities--only if we can come.

I wake up, and i am really sweating. This time i know it is real because of the weather outside of my window--i see the light and there is certainty; a superficial kind of certainty. I look out the window, and i see the waste bin where the corpse the woodpecker lies: i can see maggots, horse flies, insects, spiders, snakes, and a lack of opportunity. For all of the opportunity present is all that is inherited from the predators of the woodpecker, including myself, and all of those creature in the waste bin. And as all predators do, we shall carry the toxin burden of all that we prey on. For, in a twisted sense, I preyed on the woodpecker by not letting it die, praying that it will be the impetus that will bring certainty into my life. But instead, it reminds me of the opportunity that lies in the enigmatic storm of life; in a very unorthodox and painful way, through a knocking, a knocking that everyone feels. A knocking to tell you when you need to follow the connecticut winds pointing north, way deep in the beast of the unknown enigmatic storm, or follow the warm part that leads you to the west where seemingly nothing is to be found--but there is still no defining certainty.

I open my eyes from the brief resting of my eyes, and after all of those memories raced passed by me, the knocking in my head disappears. My friend is still looking into the darkness of the storm that already passed us, yet he must depart to soon, inevitably leaving us. I lean over on the bench we are sitting on, and a playfully hit him on the shoulder and say nothing. His deep thought, or lack of deep thought thereof that is a consequence of staring into the oppurtunity of the enigmatic storm too much, suddenly, disappeared. I give him a smile, as his countenance of confusion is glaring right at me with his eyebrows raised, and i say: “The storm passed, and we will embrace the next when it comes--but for now, look at the scenery”. He is comforted, and begins to look at all of the intricacies of the lake: the rays of the sun penetrate through the dark clouds providing his body with comforting warmth, and he feels an immense amount of wonderment as the ospreys so gracefully yet confidently soar above the lake, looking for food.  the tranquilizing feeling of the orange-yellow sky fills his skin with life, and he closes his eyes and holds his girlfriend tighter, as tight as possible knowing the inevitability of the big storm to arrive. Bryan feels the knocking in his head as well, we all do as a species, a knocking that will guide him through the storm, all the way through until he reaches a New Haven, for him to grow, develop, and mature. 

# The Mulberry Tree

The Godly product of the Sun’s nuclear fusion began to travel the seemingly endless and Skeptic void of
outer space, being the omnipotent force that so conspicuously displays its prowess by derisively granting an
evidently perfect and pure life. Its light continues to travel through the stratosphere in a quaint and transparent
manner that fails to obtain the attention of even the sharpest life form. However this does not impede in its
grandiloquent quest to strike the organism I rest on at 186,000 miles per second, creating a product far greater
than the majestic process of hydrogen colliding at the Sun’s core. The weak shadow of a Mulberry Tree.
I rested atop the firm and indestructible branch of the Mulberry Tree as I so regally admired the
beauteous clouds that floated ever so faultlessly above me. I began to envision a future that seemed so vivid and
profound that only I can make palpable, a ship that would be able to travel ceaselessly through the sea of clouds,
being higher than the span of wind itself where I, and only I, am left to propel the sail with my own ambition and
vision. A ship that is eternally drifting through an unseen world that must be traversed in order to discover the
truth that lies so surreptitiously in this world full of skepticism; the only way to objectively see, is to eliminate the
superincumbent veil of fog that exists above humanity.

I blink. Then thus do I continue to ponder the immensity of purpose that superencumbently perplexes me.
Subsequently, this overwhelming impetus to define my purpose -- which by nature spawns at an infinitum -- must
be addressed considering I have two more years till I am unscrupulously eliminated, by Sir Bunty himself, from this
safe haven that has heretofore defined my morality, values, and necessity for me to help humanity. Suddenly the
branch I sat on began to grow frail and foundationless, and time began to progress at a rate as slow as the growth
of fungus on a loaf of bread. I, for the millionth time, began to reexamine all of the possibilities that are so
profusely imperative for me to bolster and aid the collective good of humanity that will utilize my abilities
optimally: a professor or educator, who can terminate the contagion of ignorance that resides within this reality, a
law enforcement officer, who can extricate all of the incontrovertible shortcomings that are ubiquitously present
in this world, or an attorney of law, who is the eloquent elucidator of indubitable truth that is present within the
action a victim or persecutor is subjected to; I feel the weight of possibility that lies in the future that is currently
nebulous due to my fundamental indecisiveness chaining me down. The chain begins to manifest onto my physical
body, restraining me and hurting me, as the rust of Skepticism that is omnipresent in this possibility overwhelms --
I blink. I look down at my arms and hands, then to the world around me as I sense the virus of skepticism
beginning to slowly seep out of my body into the gloomy and doleful fog that exists around me and humanity thus
extricating me from my doubt. I begin to obtain my will to rationally contemplate and decide once more, and I feel
as if my ability to decide was once again restored upon me by some unknown entity that has a form that is
heretofore defined as amorphous. My muscles begin to relax as a gale of warm air comforts and massages my skin
as it, ever so slowly, flows with some purpose or reason that is currently elusive to me. I begin to blink at a normal
pace once again as I regain my will. I struggle to look into the horizon that seems to be fundamentally unclear due
to the grudgingly overpowering fog that curses the world around me, I re-embark into my journey to become what
humanity expects from me. Altruistically dedicating all I can in order to help the collective; considering, I am just
one component that plays an infinitesimal role in developing the holistic identity.

Once more do I blink. I hold it for a few extra seconds this time, attempting to grasp onto the platonic
shadow of time as I adamantly attempt to linger in the moment; I, ostensibly, feel as if I am transcending the reality
in which I am trapped in for just a few short seconds. However, I only obtain the privilege to metaphysically caress
the concept I have hitherto heavily romanticized yet utterly despised, thus leaving a bitter sweet feeling on the tip
of my tongue. I open my eyes, and respawn myself onto the physical. I finally extricate myself from my quixotically
driven dream due to the noise that pierced my sacred silence, imploring a countenance of general disdain.
“Daulter! Mind if you come down to talk? You have isolated yourself since brunch this morning.” he
uttered in an attempt to obtain my attention.
“Sure. give me one second.

# The Daulter Dillemma 

I hop out of the shower, soap dripping down the hairs behind my leg as I almost slip on my old bath mat overlayed with a frog pattern. I grab the stained towel resting atop my toilet, quickly drying my hair as the podcast discussing Plato’s Symposium is interrupted by the piercing sound of my alarm reminding me I am 15 minutes behind schedule. Alarm singing, I squint my eyes as if I can look past the fog lying between my mirror and the Daulter the world will see, trying to fix my hair. I give up, grab my phone, and throw the towel back on the toilet, missing completely, for tomorrow’s use.

 I run out the bathroom door to my dresser, letting out a mist that dissipates immediately. I jump into a pair of underwear, slide on some mismatched dress socks absorbing the soapy water between my toes, put deodorant on, struggle putting on my tight jeans through my undried legs, force on my brown dress shoes without the time to tie them, and button down my short-sleeve dress shirt patterned with small forget-me-nots contrasted on black. I grab my black backpack that is thrown on the floor with all of my other clothes, lying between my copy of Nietzsche’s “Twilight of the Idols” and Kierkegaard’s “Fear and Trembling”. I stop for a second, staring at Isaac’s eyes screaming for help through the “Penguin Classics” cover art displaying Abraham’s hand holding his throat to the floor, while he is pressing a rusted knife against his young son’s fair skin with the other. I pause for a second, literally. I quickly realize it is the muffled noise of my phone alarm in my pocket screaming, not Isaac, reminding me I don’t have time to shit around and I grab the book with me. 

I sprint to the other side of my poorly lit studio apartment, grabbing everything I can on the way; I pass the kitchenette and walk through the door as I am blinded by the San Diego sun. I cover my face with my hands from the Sun’s truthful presence, hiding just behind its shadow so I can see; I run down the stairs, pass the un-pressure washed concrete floor, and dive into my faded-black 2012 Toyota Corolla’s driver seat. I turn on the car, turn off the cursed chorus of a fucking phone alarm, and drive out of my complex toward the class I have at 9:30 am in Late modern Philosophy. Startling me, my phone syncs with the bluetooth stereo in my car resuming the podcast on the Symposium. The soft, yet crass, tone of the podcaster’s voice emanates through my car resuming his description of Aristophanes account of love that is different from that of Phaedrus, Pausanias, and Eryximachus. 

I place my arm on the passenger seat while looking back, and I reverse the car out of my parking spot to then propel forward like a torpedo. I roll down the windows and briefly look outside at the blue sky which is ever so slightly sprinkled with cotton-candy clouds. Distracted by the clouds, I finally refocus and tune back into the podcast.  

>“Aristophanes’ account of love in the symposium is fitting for his role as a comedian, some even argue it is to be interpreted as a joke! He proposed humans existed with two arms and two legs, toiling and rolling around the earth with power that could even challenge those of gods! Zeus grew jealous and smote humans in half with his righteous bolts, separating them from their original soul mate. For this reason human’s always feel a gripe of loneliness, and love is finally being able to reunite with your lost half. That is why they say!—when you lock eyes with your true love, you can’t help but feel a pang of familiarity and nostalgia.

I drop my hand out the window while racing down I15 to UCSD. I turn toward my left seeing a glimpse of the glistening california coastline in the distance. “Huh, so i'm just here to look for my other half? Who is to say you would ever meet them? What are the chances?” At the thought of that the light of the sun reflects from a bright red volkswagen speeding up behind me, into my mirror, then to my eyes. Slightly blinded, I bring my hand from outside to cover my eyes. I open them and see something in the sky. I see two dense clouds, nearly touching but not quite; and a stream of celadon-blue sky between them. It almost looks like Zeus’ lighting bolt, but I notice it is a little too water-like to come from his sky. Almost looking like a river of some sort. I rub my eyes, and the pain of the glare is gone. I look back and see the clouds part quickly as the ocean breeze pushes them astray. I lock my attention back on the road watching my eyes melt with the asphalt as I drive; and I continue to listen to the podcast till I get to school

<center>*</center>

Me rapidly turning then breaking into this parking spot woke me from my trance. I hear a fleeting scream: “That was my fucking spot! I turn around seeing a guy driving away with a porcelain-white Tesla, wearing what looks like some designer black shades. I look on the passenger seat, and see the print out of my class schedule sticking out of my blue 99-cent notebook I bought at Wal-Mart. I grab the notebook, pulling the schedule out; I grab my bag, putting it over my shoulders. And I step out of my car. I almost forgot how bright the sun is today but I quickly remembered—speaking of remembering! I put my hand down my car’s side door knowing just where to grab my drakkar noir without getting the dirty napkins I left there a couple of days ago. I spray some on, throw it back in the car, and pace across the parking lot to get to—I check my schedule—Pepper Canyon Hall. I almost walk into a blue honda civic impatiently sitting there with their turn signals where I quickly evade it and haste over to the crosswalk. The traffic guard raises his hand gesturing us to cross, where I gently jog down the road, through the bushes and grass, and in front of the Pepper Canyon Hall. I walk through the two automatic doors, and feel the chill of the air-conditioned air pierce right through my fore-head sweat. I part my hair back while looking for room—I check my schedule—119; I quickly find it and check my watch: 9:24. Im six-minutes early. 

I go to reach for the door and feel a strong female presence right when I touch the cold brass door hinge. I open the door, instinctively exclaiming “After you!”. She had, serially, given me a quick glance, then walked through the door saying “thanks”. Like the eyes of a gorgeous greek gorgon, I found them petrifying me. brown at first glance; but upon further inspection painted with streaks of silver and splashes of olive.  I became aware of how dry my throat was, and froze right before uttering “your welcome—”. She was already half-way toward the front row of seats. She walked with a demanding presence: silent yet cunning. She had curly black hair, unkept; soft vanilla exterior, abyssal interior. She was wearing hot-pink rain boots, baggy faded-blue jeans, a large black men’s T-shirt—tucked in—with what looks like an unlit fire-fly on black, and a sterling silver necklace with an onyx pendant. I walk on over, thinking if I should sit next to her, but at the risk of not being weird I sit one seat over. 

I pull out my blue notebook, my copy of fear and trembling, and a 20mg Adderall IR that I take with no water. She glares at me, about to open her mouth to speak. My heart skips a beat. Does she read Kierkegaard? She seems like the type; I am aroused by the thought. In a monotone voice, she says “Hey, saw you pop an addie, wanna pass one over”? I feel an unprecedented force. It felt like the part of my brain responsible for my autonomy, which I didn’t even think existed, was immobilized by something. My hand, with a consciousness of one that wasn't it’s nor mine, reaches into my bag grabbing an adderall pill. I hand it over and place it on her hand. Her hand is softer than any I have touched. But it injected and ancient coldness through my body leaving a lingering feeling that I can’t shake off. She smiles at me, turns toward the front, and drinks some water to “pop the addie”. Mid-glance, some guy aggressively sits between us in the empty seat. He looks at me, giving me a contempt smirk, and says “Sorry did I interrupt”? I look at him in the face, trying to remember where he is from. Then I realize: Royal-Purple Gucci sunglasses in doors—it’s white-tesla guy from earlier. 

People start to rush in and fill the seats of the classroom. I see a dude walking down my row to sit next to me: He’s about five-seven, skin embodying the essence of hawaiin-brown palms, and the demarcation between his obsidian-black head hair and facial hair is to be unseen. He is wearing light-gray sweatpants, dirty checkered vans, and a tank top with a psychedelic explosion stemming from a mario mushroom. His eyes lock with mine, and it feels like he presents his soul through his eyes. He takes a seat and brings his hand from his pocket toward me for a handshake, “the name’s Kai, nice to meet you bro!” I shake his hand, “Hey! I’m Daulter”—before I can finish, he reaches awkwardly across my note-book and grabs the Kiekegaard. “Woah dude, you read Kiekegaard? Did you know he had, like, a hard time balancing his girl and philosophizing? Makes sense if you ask me, how else could his writing sound like he is always in despair. Sometimes, man, you just gotta remember to enjoy what’s in front of you. That’s all that's really there ya know?”. He pauses for a second, blankly staring at the board. He reaches into his pocket, pulling out a golden vape-pen gesturing his face toward it with his eyes on me, implying if I would like a hit or something. I grow a little nervous and shake my hand gesturing I am not interested while still trying to thank him for the offer. 

The professor walks in, carrying nothing with him other than an expo marker. He is wearing a tight black shirt, tight navy-blue jeans, and black pumas with streaks of gold. His hair has a salt-pepper look that compliments his sterling silver glasses. He writes on the board:

****
<center>**George Berkeley (1685-1753)**</center>
<center>**A Treatise Concerning the Principles of Human Knowledge, 1710**</center>
<center>**Three Dialogues between Hylas and Philonous, 1713**</center>
****
      
He turns toward the class, head slightly angled toward the ceiling as if he is looking up but not quite. Everyone in the classroom is silent, slightly confused. No introduction, no syllabus. He closes the expo marker pointing it on his chin:

> Berkeley is a little difficult for me—or anyone with a brain for that matter!— to take seriously. His main thesis? Matter is non-existent. The world is nothing but immaterial, whatever that means. He articulated this argument in his rather loquacious work: The Treatise Concerning the Principles of Human Knowledge. Scholars did not receive his work well. In response, just like a underaged college student who just asked someone why they should get them liquor after they said no the first time, he reiterated his exact argument but through a dialogue this time. You all know where this is going! So there are two interlocutors: Philonous (or “lover of mind”), and Hylus (or “Matter”). The dialogue is Philonous, the great berkeleian hero! making Hylus, the embodiment of all things atheist, skeptic, and dare I saw it—Material! Cower in a corner agreeing with everything Berkeley—I meant philonous!—has to say.

My eyes follow the professor as he paces across the front of the room and back, speaking with much fervour and excitement. I open my notebook, checking my pockets where I usually keep all of my pens, and find nothing but ink stains. I panic a bit, turning toward tesla guy—distracted on his phone; he has a dark-ruby fountain pen laying on his leather notebook, and an open 50ml bottle of ink labeled “Waterman - Paris”. I can’t ask him for a pen. I turn toward Kai. He is looking right at the professor, with a kind of wonder a child looks with when looking at a new toy; nothing lying on his desk. I whisper: “Hey Kai, do you have a pen I can borrow?” He looks toward me and smiles, “of course man!” he says a little too loudly. He reaches into his bag pulling out what seems like his only pen: a dark-green pilot G2 pen. He hands it over saying “I don’t need it anyway, your mind is like a sponge. it can absorb everything you need it to”. I open my notebook, and start to take down notes while listening to the professor talk.


> Philonous provides a simple argument against matter which goes as follows:
>
>  1. We perceive ordinary objects (houses, mountains, etc.)
>  2. We perceive only ideas. \
>  ____________________________________________________________
> 
>  3. Ordinary objects are ideas.
>
> Your intuition may be to attack premise two. However, this is complicated by “The Explanatory Gap”. Just because we perceive a sensible object like an ice-cream sandwich when you got the munchies, that doesn’t necessarily mean you have direct access to the ice-cream sandwich, proper. The ice-cream sandwich is mediated by our subjective perception of it: feeling the chocolate stick to your fingertips, seeing the cold vapor emanate from it when upon it leaving the freezer, tasting the contrasting flavors of sweet vanilla with dark chocolate. Thus, we can’t say it is anything more than just an “idea”. Consciousness, whether you call it physical or immaterial, is the greatest barrier from the actual world; and Berekely takes advantage of this saying perhaps what lies beyond this “gap” was never something physical in the first place. Maybe the ice-cream sandwich, proper, was always just an “idea”. 

# My Hero Academia 

My favorite TV show is my hero academia. In this show, approximately 90% of the population has something known as a “quirk” which is a hidden ability people are born with. This can include something simple such as the ability to attract small objects toward you, or heat things up when you touch them. However, given that people with these quirks contain hidden power, they can use it for evil or for good. Thus, one pivotal part of this society is that there are heros that are hired to fend crime. The number one hero being All Might: he contains super strength, unmitigating charisma, and the ability to save anyone no matter how dire the situation. The main character, Midoriya, idolizes All Might and aspires to be a hero like him; however, he is one of the few people in this society that does not have a quirk. One fateful day however, he sees one of his friends being threatened by a villian, and despite not having any powers, he charged in ready to rescue him even though he had no logical way to win. All might eventually interrupts and saves the day, and upon All Might seeing the vivacity in his conviction to be a hero, despite the world saying it is impossible for him to do so, he gifts Midoriya with his power. The story of this show then is how Midoriya uses this power to become the number one hero. What I think draws me to this show is seeing how raw conviction always pays off, so much that it can even surpass what is physically possible. One motto of the show is not only to “go beyond” but to “go beyond - plus ultra”. In so far as you keep challenging yourself, and keep going, you will eventually attain what you want. Being the best isn't about gift, it is about determination. And when I watch this show, I feel like it relates most to my academics. When I was younger, I was never part of the intelligent group of kids. However, once I went to highschool I made it my heart felt goal to become an academic, and eventually become a professor. Like the hero field in my hero academia, it is overly saturated and difficult to succeed in this field. But as long as I am like Midoriya and put in my 100%, plus ultra, I can attain my goal. 




```{r setup, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="25")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=25)
```

